"""empty message

Revision ID: 3e967216f7e6
Revises: f5467fdc2718
Create Date: 2019-01-17 17:23:13.254876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e967216f7e6'
down_revision = 'f5467fdc2718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('sentiment', sa.String(length=380), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweet', 'sentiment')
    # ### end Alembic commands ###
