"""empty message

Revision ID: 732e400dd8a3
Revises: 3e967216f7e6
Create Date: 2019-01-17 18:37:36.712969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732e400dd8a3'
down_revision = '3e967216f7e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('subjectivity', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'subjectivity')
    # ### end Alembic commands ###
