"""empty message

Revision ID: cd6d05ad3395
Revises: 732e400dd8a3
Create Date: 2019-01-18 15:44:18.545747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6d05ad3395'
down_revision = '732e400dd8a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('sentiment2', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'sentiment2')
    # ### end Alembic commands ###
