"""empty message

Revision ID: f5467fdc2718
Revises: e0e17dc830f7
Create Date: 2019-01-17 16:12:50.867741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5467fdc2718'
down_revision = 'e0e17dc830f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('entities', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'entities')
    # ### end Alembic commands ###
